name: latihan_get
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  dio: ^5.0.0
  get_storage: ^2.0.3
  google_fonts: ^4.0.3
  hexcolor: ^3.0.1
  http: ^0.13.5
  lottie: ^2.2.0
  webview_flutter: ^4.0.5
  url_launcher: ^6.1.10

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets: 
    - assets/images/

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand/Quicksand-VariableFont_wght.ttf
        - asset: assets/fonts/Quicksand/static/Quicksand-Light.ttf
          weight: 300
        - asset: assets/fonts/Quicksand/static/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/Quicksand/static/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand/static/Quicksand-Bold.ttf
          weight: 700

